- rule: "rpc.enable?"
  description: "Must have an RPC enabled"
  suggestions:
    - SET:
        var: "rpc.enable"
        to-value: true
- rule: "advanced.blockfilters.blockfilterindex?"
  description: "Must have block filter index enabled for Run The Numbers to work"
  suggestions:
    - SET:
        var: "advanced.blockfilters.blockfilterindex"
        to-value: true
- rule: "!(#rpc.advanced.threads < 2)"
  description: "Must be >= 2"
  suggestions:
    - SET:
        var: "rpc.advanced.threads"
        to-value: 2
