- rule: '''users.*.name = "specter-desktop"'
  description: 'Must have an RPC user named "specter-desktop"'
  suggestions:
    - PUSH:
        to: "users"
        value:
          name: specter-desktop
          allowed-calls: []
          fetch-blocks: false
    - SET:
        var: 'users.[first(item => ''item.name = "specter-desktop")].password'
        to-entropy:
          charset: "a-z,A-Z,0-9"
          len: 22
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getindexinfo"'
  description: 'RPC user "specter-desktop" must have "getindexinfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getindexinfo"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getblockcount"'
  description: 'RPC user "specter-desktop" must have "getblockcount" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getblockcount"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getchaintips"'
  description: 'RPC user "specter-desktop" must have "getchaintips" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getchaintips"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getmempoolinfo"'
  description: 'RPC user "specter-desktop" must have "getmempoolinfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getmempoolinfo"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getblockchaininfo"'
  description: 'RPC user "specter-desktop" must have "getblockchaininfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getblockchaininfo"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getblockhash"'
  description: 'RPC user "specter-desktop" must have "getblockhash" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getblockhash"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getblock"'
  description: 'RPC user "specter-desktop" must have "getblock" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getblock"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getmempoolentry"'
  description: 'RPC user "specter-desktop" must have "getmempoolentry" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getmempoolentry"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getrawtransaction"'
  description: 'RPC user "specter-desktop" must have "getrawtransaction" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getrawtransaction"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getrawmempool"'
  description: 'RPC user "specter-desktop" must have "getrawmempool" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getrawmempool"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "gettxout"'
  description: 'RPC user "specter-desktop" must have "gettxout" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "gettxout"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "validateaddress"'
  description: 'RPC user "specter-desktop" must have "validateaddress" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "validateaddress"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "estimatesmartfee"'
  description: 'RPC user "specter-desktop" must have "estimatesmartfee" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "estimatesmartfee"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getbestblockhash"'
  description: 'RPC user "specter-desktop" must have "getbestblockhash" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getbestblockhash"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getblockheader"'
  description: 'RPC user "specter-desktop" must have "getblockheader" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getblockheader"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getinfo"'
  description: 'RPC user "specter-desktop" must have "getinfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getinfo"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getmempoolinfo"'
  description: 'RPC user "specter-desktop" must have "getmempoolinfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getmempoolinfo"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getnetworkinfo"'
  description: 'RPC user "specter-desktop" must have "getnetworkinfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getnetworkinfo"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getpeerinfo"'
  description: 'RPC user "specter-desktop" must have "getpeerinfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getpeerinfo"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getrawtransaction"'
  description: 'RPC user "specter-desktop" must have "getrawtransaction" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getrawtransaction"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "sendrawtransaction"'
  description: 'RPC user "specter-desktop" must have "sendrawtransaction" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "sendrawtransaction"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "uptime"'
  description: 'RPC user "specter-desktop" must have "uptime" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "uptime"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "scantxoutset"'
  description: 'RPC user "specter-desktop" must have "scantxoutset" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "scantxoutset"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "listwallets"'
  description: 'RPC user "specter-desktop" must have "listwallets" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "listwallets"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getblockfilter"'
  description: 'RPC user "specter-desktop" must have "getblockfilter" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getblockfilter"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "listwalletdir"'
  description: 'RPC user "specter-desktop" must have "listwalletdir" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "listwalletdir"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "createwallet"'
  description: 'RPC user "specter-desktop" must have "createwallet" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "createwallet"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "gettxoutsetinfo"'
  description: 'RPC user "specter-desktop" must have "gettxoutsetinfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "gettxoutsetinfo"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "importdescriptors"'
  description: 'RPC user "specter-desktop" must have "importdescriptors" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "importdescriptors"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "listlabels"'
  description: 'RPC user "specter-desktop" must have "listlabels" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "listlabels"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getwalletinfo"'
  description: 'RPC user "specter-desktop" must have "getwalletinfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getwalletinfo"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "listtransactions"'
  description: 'RPC user "specter-desktop" must have "listtransactions" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "listtransactions"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getbalances"'
  description: 'RPC user "specter-desktop" must have "getbalances" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getbalances"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "listlockunspent"'
  description: 'RPC user "specter-desktop" must have "listlockunspent" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "listlockunspent"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getreceivedbyaddress"'
  description: 'RPC user "specter-desktop" must have "getreceivedbyaddress" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getreceivedbyaddress"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "listsinceblock"'
  description: 'RPC user "specter-desktop" must have "listsinceblock" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "listsinceblock"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "rescanblockchain"'
  description: 'RPC user "specter-desktop" must have "rescanblockchain" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "rescanblockchain"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "loadwallet"'
  description: 'RPC user "specter-desktop" must have "loadwallet" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "loadwallet"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "gettransaction"'
  description: 'RPC user "specter-desktop" must have "gettransaction" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "gettransaction"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "walletprocesspsbt"'
  description: 'RPC user "specter-desktop" must have "walletprocesspsbt" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "walletprocesspsbt"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "setlabel"'
  description: 'RPC user "specter-desktop" must have "setlabel" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "setlabel"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "walletcreatefundedpsbt"'
  description: 'RPC user "specter-desktop" must have "walletcreatefundedpsbt" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "walletcreatefundedpsbt"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "listunspent"'
  description: 'RPC user "specter-desktop" must have "listunspent" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "listunspent"
- rule: '''users.[first(item => ''item.name = "specter-desktop")].allowed-calls.* = "getmininginfo"'
  description: 'RPC user "specter-desktop" must have "getmininginfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "specter-desktop")].allowed-calls'
        value: "getmininginfo"
