# To utilize the default config system built in the compat system image, this file is required. It defines the *structure* of the configuration file. These structured options display as changeable UI elements within the "Config" section of the service details page in the Embassy UI

# tor-address:
#   name: Network Tor Address
#   description: The Tor address for the network interface. 
#   type: pointer
#   subtype: package
#   package-id: specter-desktop
#   target: tor-address
#   interface: main
# lan-address:
#   name: Network LAN Address
#   description: The LAN address for the network interface. 
#   type: pointer
#   subtype: package
#   package-id: specter-desktop
#   target: lan-address
#   interface: main
specter-desktop:
  type: union
  name: Specter Desktop Mode
  description: Server or Bitcoin Core mode for Specter Desktop
  tag:
    id: mode
    name: Type
    description: |
      - server: Server Mode
      - bitcoind: Bitcoin Core API Mode
    variant-names:
      server: Server
      bitcoind: Bitcoin Core
  default: server
password:
  type: string
  name: Specter Desktop Password
  description: Administrator password for Specter Desktop
  nullable: false
  copyable: true
  masked: true
  default:
    charset: "a-z,A-Z,0-9"
    len: 22
bitcoind:
  type: union
  name: Bitcoin Core RPC for Faraday
  description: The Bitcoin Core node for Faraday to connect to
  tag:
    id: type
    name: Type
    description: |
      - Internal: The Bitcoin Core service installed to your Embassy
      - Internal Proxy: The Bitcoin Proxy service installed on your Embassy
    variant-names:
      internal: Internal
      internal-proxy: Internal (Bitcoin Proxy)
  default: internal
  variants:
    internal:
      user:
        type: pointer
        name: RPC Username
        description: The username for the RPC user for Bitcoin Core
        subtype: package
        package-id: bitcoind
        target: config
        selector: "$.rpc.username"
        multi: false
      password:
        type: pointer
        name: RPC Password
        description: The password for the RPC user for Bitcoin Core
        subtype: package
        package-id: bitcoind
        target: config
        selector: "$.rpc.password"
        multi: false
    internal-proxy:
      user:
        type: pointer
        name: RPC Username
        description: The username for the RPC user allocated to Specter Desktop
        subtype: package
        package-id: btc-rpc-proxy
        target: config
        multi: false
        selector: '$.users.[?(@.name == "specter-desktop")].name'
      password:
        type: pointer
        name: RPC Password
        description: The password for the RPC user allocated to Specter Desktop
        subtype: package
        package-id: btc-rpc-proxy
        target: config
        multi: false
        selector: '$.users.[?(@.name == "specter-desktop")].password'