name: Release Service

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  ReleasePackage:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare StartOS SDK
        uses: Start9Labs/sdk@v1

      - name: Checkout services repository
        uses: actions/checkout@v4

      - name: Build the service package
        id: build
        run: |
          git submodule update --init --recursive
          start-sdk init
          make
          PACKAGE_ID=$(yq -oy ".id" manifest.*)
          echo "package_id=$PACKAGE_ID" >> $GITHUB_ENV
          printf "\n SHA256SUM: $(sha256sum ${PACKAGE_ID}.s9pk) \n"
        shell: bash

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: ./${{ env.package_id }}.s9pk
